### ISSUE TITLE
Endpoint not working on localhost

### ISSUE THREAD

**Issue by duplich** [tim-field/graphql-wp#19]
Hi there, 
I am following your tutorial: 
- installed wordpress via bedrock
- installed ChromeiQL extension
- configured wordpress to run under http://bedrock.dev on windows machine

But I can not get the endpoint to run
- Full endpoint path: http://bedrock.dev/graphql
- Query: 
`query PostQuery{
wp_post(ID: 1) {
    title
  }	
}`
- output: 
`SyntaxError: Unexpected token < in JSON at position 0`

Does anyone know what (probably simple) configuration I am missing?
Thanks in advance

**Comment by duplich** [comment]
Forget about it, It was a silly mistake of not activating the plugin in admin dashboard :) 
But you shall mention it in the Installation process that it is to be activated as a normal plugin and I assumed it is autoactivated through autoload.php 
Greetings

**Comment by deemaxx** [comment]
I am getting the same error despite the activated plugin. The console does output a parse error which points to the usage of a PHP7 null coalescing operator (??):
`Parse error</b>:  syntax error, unexpected '?' in <b>/wordpress/web/app/plugins/graphql-wp/Type/Definition/WPPost.php`

I am running a Docker container on PHP5.6. The graphql-wp repo's composer.json file requires php>=5.6. So, maybe it requires now PHP7. But, I am confused because no one has mentioned this anywhere.
